confluentinc/confluent-kubernetes-examples

- hybrid/ccloud-integration/creds-client-kafka-sasl-user.txt
- hybrid/ccloud-integration/creds-schemaRegistry-user.txt
updated creds value to api-key and api-secret
> Updated creds value to api-key and api-secret

- security/production-secure-deploy/README.rst
> Replace k alias with kubectl

- general/cp-version/confluent-platform-6.0.0.yaml
- general/cp-version/confluent-platform-6.1.0.yaml
- general/cp-version/confluent-platform-6.2.0.yaml
This PR provides a CR yaml example for each CP version release - 6.0, 6.1 and 6.2.
> Add CRs with CP Docker images for each release

- assets/openldap/values.yaml
To allow the creation of ldifs in the correct sequence we need to number them.
> ldifs changes

- security/plaintext-basic-auth-control-Center/README.rst
- security/plaintext-basic-auth-control-Center/basic.txt
- security/plaintext-basic-auth-control-Center/confluent-platform-ccc-basic-auth.yaml
- security/plaintext-basic-auth-control-Center/producer-app-data.yaml
This PR outline none TLS setup with Basic auth to control Center
> Control Center and Basic Auth setup

- security/plaintext-basic-auth-control-Center/confluent-platform-ccc-basic-auth.yaml
Removed license and override log4j from c3 YAML
> Removed license and override log4j from c3 YAML

- security/plaintext-basic-auth-Connect/README.rst
- security/plaintext-basic-auth-Connect/basic-c3.txt
- security/plaintext-basic-auth-Connect/basic.txt
- security/plaintext-basic-auth-Connect/confluent-platform.yaml
- security/plaintext-basic-auth-Connect/producer-app-data.yaml
> Connect basic authn

- hybrid/replicator-cloud2cloud/README.md
- hybrid/replicator-cloud2cloud/cloudproducer.yaml
- hybrid/replicator-cloud2cloud/cloudtopic.yaml
- hybrid/replicator-cloud2cloud/components-destination.yaml
- hybrid/replicator-cloud2cloud/controlcenter.yaml
- hybrid/replicator-cloud2cloud/creds-control-center-users.txt
- hybrid/replicator-cloud2cloud/destination-creds-client-kafka-sasl-user.txt
- hybrid/replicator-cloud2cloud/destination-creds-schemaRegistry-user.txt
- hybrid/replicator-cloud2cloud/source-creds-client-kafka-sasl-user.txt
- hybrid/replicator-cloud2cloud/source-kafka.properties
Workflow for confluent cloud to confluent cloud replication with control center in the background to look at the Monitoring Extension metrics.
> Repl ccloud to ccloud

- security/configure-with-vault/README.md
update mds publickey and tokenkeypair file names to `mds-publickey.txt` and `mds-tokenkeypair.txt`
> update mds publickey and tokenkeypair file name

- security/userprovided-tls_mtls_confluent-rbac/README.md
small change - dir name change for the initial export
> Fix Export typo

- security/userprovided-tls_mtls_kafka-acls/README.md
Adding More ACLs based on use case
> Adding More ACLs based on use case

- storage/README.md
- storage/deployment.yml
- storage/storage.yml
Please rewrite the readme! i wanted to copy down what i did and get it out here
> OPER-1471 - add simple storageclass demo

- quickstart-deploy/README.rst
- quickstart-deploy/producer-app-data-singlenode.yaml
- security/userprovided-tls_mtls_kafka-acls/README.md
When adding the producer application in the quick start we encounter min ISR limitation on the cluster with 3 brokers. 
To resolve this we added the additional yaml file and fixed rst readme.
> Fixing single node min ISR limits on quick start

- scripts/pv-resize.sh
Script is modified to handle other binary suffixes and decimals, but cannot fully support decimals depending on the k8s.
> OPER-1589 Modify Azure PV resize script to handle size unit better

- hybrid/ccloud-topic-clusterlink/README.md
- hybrid/ccloud-topic-clusterlink/clusterlink-ccloud.yaml
- hybrid/ccloud-topic-clusterlink/creds-basic-users.txt
- hybrid/ccloud-topic-clusterlink/creds-client-kafka-sasl-user.txt
- hybrid/ccloud-topic-clusterlink/creds-kafka-sasl-users.json
- hybrid/ccloud-topic-clusterlink/kafkarestclass-ccloud.yaml
- hybrid/ccloud-topic-clusterlink/passwordencoder.txt
- hybrid/ccloud-topic-clusterlink/rest-credential.txt
- hybrid/ccloud-topic-clusterlink/topic_ccloud.yaml
- hybrid/ccloud-topic-clusterlink/zk-kafka.yaml
Playbook for creating clusterlink and topic in CCLOUD. 
Link to fork's README - https://github.com/karthikeyanas/confluent-kubernetes-examples/tree/ccloud-clink/hybrid/ccloud-topic-clusterlink#basic-setup
> CFK-1647 Playbook for creating clusterlink and topic in CCLOUD [skip secret scan]

- security/production-secure-deploy/README.rst
- security/production-secure-deploy/confluent-platform-production.yaml
This reverts commit a207eeb25db5dd12304be485d1b16eab77a5dd8a.
> Revert "Clarifications to bring the CP component clusters using LB"

- blueprints-early-access/scenarios/quickstart-deploy/multi-site-deployment.rst
- blueprints-early-access/scenarios/quickstart-deploy/single-site-deployment.rst
update directory path and repo name in the single site and multi-site deployment
> update directory path and repo name

- connector/http-sink-connector/README.md
- connector/http-sink-connector/confluent-platform.yaml
- connector/http-sink-connector/httpsinkconnector.yaml
- connector/http-sink-connector/nodejs.yaml
- connector/http-sink-connector/producer-app-data.yaml
In this example we create http sink connector with validation steps
> Adding http sink connector example [skip secret scan]

- migration/connect-migration.yaml
- migration/controlcenter-migration.yaml
- migration/kafka-migration.yaml
- migration/ksqldb-migration.yaml
- migration/replicator-migration.yaml
- migration/schemaregistry-migration.yaml
- migration/zookeeper-migration.yaml
Change to the migration init container based on latest supported version
>   Change to the migration init container based on latest supported version

- hybrid/multi-region-clusters/confluent-platform/kafka/kafka-central.yaml
- hybrid/multi-region-clusters/confluent-platform/kafka/kafka-east.yaml
- hybrid/multi-region-clusters/confluent-platform/kafka/kafka-west.yaml
- security/configure-with-vault/rbac/confluent-platform-withrbac-vault.yaml
- security/configure-with-vault/rbac/zk_kafka.yaml
- security/internal_external-tls_mtls_confluent-rbac/confluent-platform-mtls-rbac.yaml
- security/production-secure-deploy-auto-gen-certs/confluent-platform-production-autogeneratedcerts.yaml
- security/production-secure-deploy-auto-gen-certs/confluent-platform-production-mtls.yaml
- security/production-secure-deploy-auto-gen-certs/confluent-platform-production.yaml
- security/production-secure-deploy/confluent-platform-production-autogeneratedcerts.yaml
- security/production-secure-deploy/confluent-platform-production-mtls.yaml
- security/production-secure-deploy/confluent-platform-production.yaml
- security/userprovided-tls_mtls-sasl_confluent-rbac/confluent-platform-mtls-sasl-rbac.yaml
- security/userprovided-tls_mtls_confluent-rbac/confluent-platform-mtls-rbac-hostbased-ingress.yaml
- security/userprovided-tls_mtls_confluent-rbac/confluent-platform-mtls-rbac.yaml
- security/userprovided-tls_mtls_confluent-rbac/kafka.yaml
https://github.com/confluentinc/confluent-kubernetes-examples/issues/82
> add userSearchBase and groupSearchBase to security/RBAC config  [skip secret scan]

- monitoring/grafana-dashboard/confluent-platform-with-ClusterLink.json
Adding a dashboard with cluster link JMX enabled
> cluster link JMX dashboard

- hybrid/multi-region-clusters/internal-listeners/networking/aks/networking-AKS-README.md
- hybrid/multi-region-clusters/internal-listeners/networking/eks/networking-EKS-README.md
- hybrid/multi-region-clusters/internal-listeners/networking/gke/networking-GKE-README.md
Fixing paths in MRC internal-listeners playbook
> docs fix in MRC internal-listeners playbook

- hybrid/clusterlink/ccloud-as-source-cluster/README.md
- hybrid/clusterlink/ccloud-as-source-cluster/clusterlink-ccloud-to-cfk.yaml
- hybrid/clusterlink/ccloud-as-source-cluster/rest-credential.txt
- hybrid/clusterlink/ccloud-as-source-cluster/zk-kafka-destination.yaml
- updated README with more details
- Fixed CP CRD
- Added secret required for Kafka REST
> fixed secret references and broker CRD

- security/production-secure-deploy-auto-gen-certs/confluent-platform-production-autogeneratedcerts.yaml
Changed ZooKeeper replicas to 3.
Changed Kafka replicas to 3.
> Changed Kafka replicas [skip secret scan]

- hybrid/multi-region-clusters/external-access/README.md
DOCS: add note explaining suspected long term fix to kafka not starting up in multi region clusters
Fixes #252
> DOCS: long term fix to kafka not starting up in multi region clusters  Fixes #252

- quickstart-deploy/kraft-quickstart/README.md
- quickstart-deploy/kraft-quickstart/kraftbroker_controller.yaml
Adding kraft quickstart example without security config
> kraft quickstart deployment

- monitoring/grafana-dashboard/kraft-only-dashboard.json
- quickstart-deploy/confluent-platform-kraft.yaml
Adding Kraft Dashboard to monitoring
And also adding quick start kraft mode
> Adding Kraft Dashboard to monitoring [skip secret scan]

- security/control-center-sso/README.md
- security/control-center-sso/bearer.txt
- security/control-center-sso/c3-mds-client.txt
- security/control-center-sso/confluent-platform.yaml
- security/control-center-sso/controlcenter-rolebinding.yaml
- security/control-center-sso/creds-client-kafka-sasl-user.txt
- security/control-center-sso/creds-kafka-sasl-users.json
- security/control-center-sso/keycloak.yaml
- security/control-center-sso/ldap.txt
- security/control-center-sso/oidcClientSecret.txt
This example helps to set up single sign-on authentication for the Confluent Control Center.
> Single sign-on authentication for C3

- migration/KRaftMigration/non-secured-cluster/README.md
- migration/KRaftMigration/non-secured-cluster/confluent-platform.yaml
- migration/KRaftMigration/non-secured-cluster/kraftmigrationjob.yaml
- migration/KRaftMigration/non-secured-cluster/zookeeper.yaml
- migration/KRaftMigration/rbac-enabled-cluster/README.md
- migration/KRaftMigration/rbac-enabled-cluster/bearer.txt
- migration/KRaftMigration/rbac-enabled-cluster/confluent-platform.yaml
- migration/KRaftMigration/rbac-enabled-cluster/creds-client-kafka-sasl-user.txt
- migration/KRaftMigration/rbac-enabled-cluster/creds-kafka-sasl-users.json
- migration/KRaftMigration/rbac-enabled-cluster/creds-kafka-zookeeper-credentials.txt
- migration/KRaftMigration/rbac-enabled-cluster/creds-zookeeper-sasl-digest-users.json
- migration/KRaftMigration/rbac-enabled-cluster/kraftmigrationjob.yaml
- migration/KRaftMigration/rbac-enabled-cluster/ldap.txt
- migration/KRaftMigration/rbac-enabled-cluster/zookeeper.yaml
This example covers the zookeeper to KRaft migration using CFK https://docs.confluent.io/operator/current/co-migrate-kraft.html
> Zookeeper to KRaft Migration Example

- migration/nonRBACToRBAC/mtlsLdap/README.md
- migration/nonRBACToRBAC/mtlsOAuth/README.md
- migration/nonRBACToRBAC/mtlsOnly/README.md
- security/mds-mtls-c3-sso/README.md
- security/mds-mtls-with-vault/README.md
- security/mds-mtls/README.md
- security/mtls-rbac-with-sso-oauth/README.md
Found out there are more places where the directory path needs to be fixed. Updated the changes in this PR
> correcting typing mistake in the file path

- networking/external-access-static-port-based/ingress-service-portbased.yaml
- security/internal_external-tls_mtls_confluent-rbac/ingress-service-hostbased.yaml
> Update documentation and examples to align with current Kubernetes specifications
