confluentinc/confluent-kubernetes-examples

security/production-secure-deploy/README.rst
Rolling out this tutorial, I had the following issues :
First one:
```
$ helm upgrade --install -f $TUTORIAL_HOME/../../assets/openldap/ldaps-rbac.yaml test-ldap $TUTORIAL_HOME/../../assets/openldap --namespace confluent
Release "test-ldap" does not exist. Installing it now.
Error: create: failed to create: namespaces "confluent" not found
```
Then:
```
cfssl gencert -initca $TUTORIAL_HOME/../../assets/certs/ca-csr.json | cfssljson -bare $TUTORIAL_HOME/../../assets/certs/generated/ca -                                                                             namespace-details ✱ ◼
2021/05/17 13:30:42 [INFO] generating a new CA key and certificate from CSR
2021/05/17 13:30:42 [INFO] generate received request
2021/05/17 13:30:42 [INFO] received CSR
2021/05/17 13:30:42 [INFO] generating …
```
=> Namespace details

security/production-secure-deploy/topic.yaml
From an explain on the resource:
```
KIND:     KafkaTopic
VERSION:  platform.confluent.io/v1beta1
RESOURCE: spec <Object>
DESCRIPTION:
KafkaTopicSpec defines the desired state of KafkaTopic
FIELDS:
configs	<map[string]string>
Configs allows passing configs for topic More information about topic
configs is available here
https://docs.confluent.io/current/installation/configuration/topic-configs.html
kafkaClusterRef	<Object>
KafkaClusterRef defines the name of the kafka cluster
kafkaRest	<Object>
KafkaRestRef defines the Kafka Rest API configuration
...
```
=> Fix topic's kafkaRest field

security/production-secure-deploy/confluent-platform-production-autogeneratedcerts.yaml, security/production-secure-deploy/confluent-platform-production-mtls.yaml
`services.mds.provider.type: ldap` was missing from file [confluent-platform-production-autogeneratedcerts.yaml](https://github.com/confluentinc/confluent-kubernetes-examples/blob/master/security/production-secure-deploy/confluent-platform-production-autogeneratedcerts.yaml). 
Also, replaced the restProxy with KafkaRest in confluent-platform-production-autogeneratedcerts.yaml file.
=> updated mds provider type and replaced restProxy with KafkaRest in confluent-platform-production-autogeneratedcerts.yaml

security/production-secure-deploy/README.rst
Added commands to tear down the cluster for `production-secure-deploy` set up
=> Added commands to tear down the cluster

hybrid/ccloud-integration/confluent-platform.yaml
The hybrid scenario does not work for Control Center and the ksqldb integration. 
This is due to: 
We are marking in the C3 CRD that ksqldb has tls, which it doe not. 
We are using the wrong hostname in the URL for ksqldb in the C3 CRD. 
bug fix.
=> Bug fix for hybrid ControlCenter not showing ksqldb

hybrid/replicator/components-source.yaml
This patch fixes the error `spec.podTemplate.resources.requests.cpu in body must be of type integer: number` when applying this into k8s
=> Invalid cpu value

quickstart-deploy/producer-app-data-singlenode.yaml
Changing to an explicit topic name in the kafka-producer-perf-test command. Currently, using {HOSTNAME} does not work if the number of replicas is greater than 0, and having a topic CRD already hardcoded to elastic-0, it makes sense to have it aligned.
=> Update producer-app-data-singlenode.yaml  [skip secret scan]

quickstart-deploy/confluent-platform-singlenode.yaml
If `metricReporter.enabled` is set to `true` in the Kafka CR for single node CP deployment, Kafka logs InvalidReplicationFactorException for `_confluent-metrics` topic: 
`org.apache.kafka.common.errors.InvalidReplicationFactorException: Replication factor: 3 larger than available brokers: 1.`
Set `confluent.metrics.reporter.topic.replicas` to 1 if there is only one Kafka broker in the Kafka metrics cluster.
=> Set metrics reporter replication factor to 1

security/openshift-security/README.md
In the openshift-example cfk-operator was chosen - renamed to confluent-operator to be consistent with the documentation on the docs page and the other examples.
=> Renamed operator name in README to confluent-operator for consistency

quickstart-deploy/producer-app-data-singlenode.yaml, quickstart-deploy/producer-app-data.yaml
##Why?
The secret which is created for producer config is in the `confluent` namespace, whereas the producer is in default, so this is to fix the namespace for the producer.
Error encountered:
```
MountVolume.SetUp failed for volume "kafka-properties" : secret "kafka-client-config" not found
```
=> fix namespace from default to confluent

quickstart-deploy/README.rst
One instruction was duplicated out of place.
Also fixed the code block formatting for one command.
=> Fix README typos

hybrid/clusterlink/mtls_source_cluster/README.md, hybrid/clusterlink/mtls_source_cluster/password-encoder-secret.txt, hybrid/clusterlink/mtls_source_cluster/zk-kafka-destination.yaml, hybrid/clusterlink/sasl_ssl_source_cluster/README.md, hybrid/clusterlink/sasl_ssl_source_cluster/password-encoder-secret.txt, hybrid/clusterlink/sasl_ssl_source_cluster/zk-kafka-destination.yaml
updated `passwordEncoder` in clusterlink example, and removed `confluent.cluster.link.enable` from the configOverrides since cluster linking is enabled [by default](https://docs.confluent.io/platform/current/multi-dc-deployments/cluster-linking/configs.html#using-cluster-linking-with-co-long) starting from Confluent Platform 7.0.0
=> update passwordEncoder and remove confluent.cluster.link.enable config

networking/external-access-static-host-based/README.rst, networking/external-access-static-host-based/ingress-service-hostbased-example.yaml, networking/external-access-static-host-based/ingress-service-hostbased.yaml, networking/external-access-static-host-based/topic.yaml
ingress-service-hostbased.yaml: networking.k8s.io/v1beta1 is deprecated in Kubernetes v1.22. Currently, networking.k8s.io/v1 is only supported for the new Kubernetes versions.
README.rst: The Helm release is called "ingress-nginx" instead of "nginx-operator"
topic.yaml: In this example, the brokers are configured with "min.insync.replicas = 2". I've observed that the option "replicas: 1" makes the topic to be unavailable so the producer gets an error when trying to write to topic "elastic-0". Removing that option the issue is solved.
=> Update - external-access-static-host-based

hybrid/ccloud-JDBC-mysql-mountedVolumes/README.md, hybrid/ccloud-JDBC-mysql-mountedVolumes/ccloud-credentials.txt, hybrid/ccloud-JDBC-mysql-mountedVolumes/ccloud-sr-credentials.txt, hybrid/ccloud-JDBC-mysql-mountedVolumes/connector.yaml, hybrid/ccloud-JDBC-mysql-mountedVolumes/kafka-connect.yaml, hybrid/ccloud-JDBC-mysql-mountedVolumes/sqlcreds.txt, hybrid/ccloud-JDBC-mysql-mountedVolumes/step1-pv-volume.yaml, hybrid/ccloud-JDBC-mysql-mountedVolumes/step2-pv-claim.yaml, hybrid/ccloud-JDBC-mysql-mountedVolumes/step3-pv-pod.yaml
In this example, you'll set up the following:  
*  Deploy a self managed MySql server for the connector to utilize  
*  Self-managed Kafka Connect cluster connected to Confluent Cloud
*  Use `mountedVolumes` on the Connect component to mount the connector jar files (not via plugin or hub)
*  Install and manage the JDBC source connector plugin through the declarative `Connector` CRD  
*  Install and manage the JDBC source connector plugin through the Connect REST endpoint
=> mountedVolumes for Connect CR 

monitoring/grafana-dashboard/confluent-platform.json
the memory usage panel is doing a sum accross pods with names kafka but its not giving accurate numbers. I have added the container name and its accurate now
=> memory usage panel is not accurate

hybrid/ccloud-JDBC-vertica/README.md, hybrid/ccloud-JDBC-vertica/ccloud-credentials.txt, hybrid/ccloud-JDBC-vertica/ccloud-sr-credentials.txt, hybrid/ccloud-JDBC-vertica/connector.yaml, hybrid/ccloud-JDBC-vertica/kafka-connect.yaml, hybrid/ccloud-JDBC-vertica/sqlcreds.txt, hybrid/ccloud-JDBC-vertica/vertica-deployment.yaml
In this example, you'll set up the following:  
*  Deploy a self managed Vertica server for the connector to utilize  
*  Self-managed Kafka Connect cluster connected to Confluent Cloud
*  Install and manage the JDBC source connector plugin through the declarative `Connector` CRD using bulk mode 
*  Install and manage the JDBC source connector plugin through the Connect REST endpoint  using timestamp+incrementing mode
=> adding vertica to ccloud example via jdbc [skip secret scan] 

monitoring/grafana-dashboard/confluent-platform.json
Reverts confluentinc/confluent-kubernetes-examples#194
The json in not valid 
```
Invalid JSON!
Error: Parse error on line 542:
...,          "expr": "container_memory_us
----------------------^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'
```
=> Revert "memory usage panel is not accurate"

security/plaintext-basic-auth-ConnectAndSchemaRegistry/basicConnect.txt, security/plaintext-basic-auth-ConnectAndSchemaRegistry/basicsecretSRC3.txt, security/plaintext-basic-auth-ConnectAndSchemaRegistry/basicwithroleSR.txt, security/plaintext-basic-auth/README.rst, security/plaintext-basic-auth/client-side/basicsecretConnect.txt, security/plaintext-basic-auth/client-side/basicsecretSR.txt, security/plaintext-basic-auth/client-side/basicsecretksql.txt, security/plaintext-basic-auth/confluent-platform.yaml, security/plaintext-basic-auth/producer-consumer-app-data.yaml, security/plaintext-basic-auth/server-side/basicConnect.txt, security/plaintext-basic-auth/server-side/basicwithroleC3.txt, security/plaintext-basic-auth/server-side/basicwithroleKSQL.txt, security/plaintext-basic-auth/server-side/basicwithroleRP.txt, security/plaintext-basic-auth/server-side/basicwithroleSR.txt
The [current example](https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/security/plaintext-basic-auth-ConnectAndSchemaRegistry) for basic authN covers connect and schema registry components. However, there are some other components that also support basic authN, therefore updated the basic auth example for all the CP components. 
Also, starting with CFK 2.4.1, Control Center supports connecting to the Connect and ksqlDB cluster using basic authentication: 
- [Release notes from CFK 2.4.1 ](https://docs.confluent.io/operator/2.4/release-notes.html#co-long-2-4-1-release-notes)
=> Updating Basic Auth example for all CP components 

hybrid/multi-region-clusters/internal-listeners/confluent-platform/kafka/kafka-central.yaml, hybrid/multi-region-clusters/internal-listeners/confluent-platform/kafka/kafka-east.yaml, hybrid/multi-region-clusters/internal-listeners/confluent-platform/kafka/kafka-west.yaml
With multiple zookeepers, the chroot needs to be specified once at the end of the string in the endpoint. 
`endpoint: 
zookeeper.central.svc.cluster.local:2182,zookeeper.east.svc.cluster.local:2182,zookeeper.west.svc.cluster.local:2182/mrc
`
=> Updating zookeeper endpoint format

security/control-center-sso/README.md
Extra white space in credential secret, prevents secret from getting created correctly.
=> Extra white space in credential secret.

hybrid/replicator-cloud2cloud/components-destination.yaml
replicator extension jar version changed to v7.6.0 to match image version. Without this connect worker fails to starts with the following error:
```replicator [ERROR] 2024-04-18 03:30:33,334 [main] org.apache.kafka.connect.cli.AbstractConnectCli startConnect - Failed to start Connect
replicator org.apache.kafka.connect.errors.ConnectException: Failed to find any class that implements interface org.apache.kafka.connect.rest.ConnectRestExtension and which name matches io.confluent.connect.replicator.monitoring.ReplicatorMonitoringExtension
replicator at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugin(Plugins.java:555)
replicator at org.apache.kafka.connect.runtime.isolation.Plugins.newPlugins(Plugins.java:541)
replicator at …
```
=> replicator extension version updated to match image version

hybrid/replicator-cloud2cloud/components-destination.yaml, hybrid/replicator-source-ccloud-destCFK-tls/components-destination.yaml, hybrid/replicator/components-destination.yaml
Replicator has the following limitation:
When running Replicator with version 5.3.0 or above, set connect.protocol=eager as there is a known issue where using the default of connect.protocol=compatible or connect.protocol=sessioned can cause issues with tasks rebalancing and duplicate records.
Reference: 
https://docs.confluent.io/platform/current/multi-dc-deployments/replicator/index.html#known-issues-limitations-and-best-practices
We should take this to account and have connect.protocol=eager on the connect worker overrides.
=> replicator connect cluster should use connect.protocol=eager

assets/certs/README.md
Removing component server certificates section as the current steps are incomplete and most of this section is covered [here](https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/assets/certs/component-certs)
=> Removing component server certificates section

security/control-center-sso/README.md, security/mds-mtls/README.md
added a note from docs : https://docs.confluent.io/operator/current/co-authenticate-cp.html#co-authenticate-cp-mtls
Note that ksqlDB does not support mTLS based authentication with MDS.
=> Updated a note in mds-mtls readme.md

assets/certs/component-certs/README.md, assets/certs/component-certs/kraft-server-domain.json, security/mds-mtls-with-vault/README.md, security/mds-mtls-with-vault/app-policy.hcl, security/mds-mtls-with-vault/confluent-platform.yaml, security/mds-mtls-with-vault/controlcenter-rolebinding.yaml, security/mds-mtls-with-vault/fileUserPassword.txt
This PR adds example playbook to configure file based user store with secrets stored in Vault.
Kafka containers:
kafka config map which refers to the mounted path:
Control center login with credentials stored in vault (for example, testuser1 password1 here)
=> [CFK-3556] | Add playbook to support file based userStore with Vault

assets/certs/component-certs/kafka-server-domain.json, security/mds-mtls-c3-sso/keycloak.yaml
In our test keycloak setup, we need to manually enable authorization. This PR adds config to enable it by default. Currently only added for mtls+oauth example so as to not affect other setups.
In some of our mtls tests, we are using the same tls secret for kafka and kraft. Due to this, we also need to add kraft SN in broker's json file
=> [CFK-3616] | enable auth in keycloak setup

security/control-center-sso/confluent-platform.yaml
changed oidc to sso in the Kafka CR as oidc attribute is [deprecated](https://docs.confluent.io/operator/current/co-authenticate-cp.html#co-authenticate-c3-sso:~:text=for%20example%20configurations.-,%5B4%5D%20Deprecated.,-For%20backward%20compatibility)
=> Changing oidc to sso

migration/KRaftMigration/rbac-enabled-cluster/README.md, migration/KRaftMigration/rbac-enabled-cluster/confluent-platform.yaml, migration/KRaftMigration/rbac-enabled-cluster/creds-kafka-sasl-users.conf
[KRaft migration example for RBAC-enabled clusters](https://github.com/confluentinc/confluent-kubernetes-examples/tree/master/migration/KRaftMigration/rbac-enabled-cluster) didn't work, its throwing below error - 
```
org.apache.kafka.common.errors.ClusterAuthorizationException: Received cluster authorization error in response InboundResponse
```
After adding a controller listener to the kraftcontroller, the issue was resolved.
```
listeners:
controller:
authentication:
type: plain
jaasConfig:
secretRef: credential
tls:
enabled: true
```
=> CFK-3990 Fix kraft migration example for rbac enabled clusters
